language: java
sudo: required

# Database settings.
database:
 # the name of your JDBC driver
  driverClass: org.hsqldb.jdbcDriver

  # the username
  user: SA

  # the password
  password: 

  # the JDBC URL
  url: jdbc:hsqldb:hsql://localhost:9001
  
jdk:
- oraclejdk8
after_success:
- bash <(curl -s https://codecov.io/bash)
- nohup bash -c "cd kafka && bin/kafka-server-stop.sh config/server.properties &"
- sleep 10
- nohup bash -c "cd kafka && bin/zookeeper-server-stop.sh config/zookeeper.properties &"
addons:
  firefox: "46.0"
  hsqldb: "2.4.0"
before_install:
- wget http://apache.rediris.es/kafka/1.0.0/kafka_2.11-1.0.0.tgz -O kafka.tgz
- mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
- nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
- nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
install: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
